name: Build and publish

on:
  push:

jobs:
  private-python-package:
    name: Private python package
    runs-on: ["self-hosted", "default"]
    steps:
      - name: Private python package
        uses: batvoice-org/github-actions-private-python-package@main
        with:
          package-name: bv-uisrnn
